-- =============================================================================
-- euguide-ks materials catalog seed
-- Source checklist: Material_per_Juristat.html
-- Inserts the extracted laws, reports, guides, datasets, contacts and glossary needs
-- as CMS material entries under Sundimi i ligjit.
-- =============================================================================

delete from page_blocks
where page_slug = 'sundimi'
  and type = 'collection'
  and content->>'key' in ('materials_catalog','rule_of_law_actions');

insert into page_blocks (page_slug, type, title, content, sort_order, published) values
('sundimi', 'collection', 'Rule of law action buttons', '{"key":"rule_of_law_actions","items":[{"label_sq":"Kushtetuta e Republikës së Kosovës","href":"#/kushtetuta","variant":"dark"},{"label_sq":"Ligjet themelore","href":"#/ligjet-themelore","variant":"light"},{"label_sq":"Katalogu i materialeve","href":"#/katalogu-materialeve","variant":"light"}]}'::jsonb, 31, true);

with raw(category, title, material_type) as (
  values
    ('Objektivat për Integrimin në BE', 'Lista e plotë e të gjitha objektivave që Kosova duhet të plotësojë për anëtarësim', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Për secilin objektiv: emri, përshkrimi, kushtet, statusi (i plotësuar / i paplotësuar), data e plotësimit, burimi zyrtar', 'Material referues'),
    ('Objektivat për Integrimin në BE', '35 kapitujt e negociatave (Acquis Communautaire) — statusi për secilin', 'Objektiv / integrim BE'),
    ('Objektivat për Integrimin në BE', 'Kriteret e Kopenhagenit', 'Objektiv / integrim BE'),
    ('Objektivat për Integrimin në BE', 'Roadmap-i për liberalizim vizash (95 kriteret)', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'MSA — Marrëveshja e Stabilizim-Asociimit', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Aplikimi për statusin e vendit kandidat', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Kapitulli 23 — Sundimi i Ligjit', 'Objektiv / integrim BE'),
    ('Objektivat për Integrimin në BE', 'Kapitulli 24 — Drejtësia, Liria, Siguria', 'Objektiv / integrim BE'),
    ('Objektivat për Integrimin në BE', 'Reforma e Administratës Publike', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Kriteret Ekonomike', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Kriteret Demokratike', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Përafrimi me Acquis Communautaire', 'Objektiv / integrim BE'),
    ('Objektivat për Integrimin në BE', 'Njohja nga 5 shtetet anëtare të BE-së (Spanja, Greqia, Rumania, Sllovakia, Qipro)', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Dialogu Kosovë–Serbi', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Marrëveshja e Ohrit / Brukselit', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Asociacioni i Komunave me Shumicë Serbe', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Anëtarësim në organizata ndërkombëtare (KE, OKB, NATO, etj.)', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'Programi IPA III (Instrumenti për Asistencë Para-Anëtarësim)', 'Objektiv / integrim BE'),
    ('Objektivat për Integrimin në BE', 'Pjesëmarrja në programet e BE-së (Erasmus+, Horizon Europe, Creative Europe)', 'Material referues'),
    ('Objektivat për Integrimin në BE', 'SEPA — Single Euro Payments Area', 'Objektiv / integrim BE'),
    ('Objektivat për Integrimin në BE', 'Roaming i lirë me BE-në', 'Material referues'),
    ('Aktet Themelore', 'Kushtetuta e Republikës së Kosovës (me të gjitha amendamentet)', 'Akt ligjor / kod'),
    ('Aktet Themelore', 'Kodi Penal i Kosovës', 'Akt ligjor / kod'),
    ('Aktet Themelore', 'Kodi i Procedurës Penale', 'Akt ligjor / kod'),
    ('Aktet Themelore', 'Kodi Civil i Kosovës', 'Akt ligjor / kod'),
    ('Aktet Themelore', 'Kodi i Procedurës Civile', 'Akt ligjor / kod'),
    ('Aktet Themelore', 'Ligji për Procedurën e Përgjithshme Administrative', 'Akt ligjor / kod'),
    ('Aktet Themelore', 'Kodi Doganor dhe i Akcizave', 'Akt ligjor / kod'),
    ('Aktet Themelore', 'Kodi Rrugor', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji i Punës (dhe amendamentet)', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Tatimin mbi Vlerën e Shtuar (TVSH)', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Tatimin në të Ardhura Personale', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Tatimin në të Ardhura të Korporatave', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Sigurimet Shëndetësore', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Sigurimin Pensional', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Familjen', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Trashëgiminë', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Pronësinë dhe të Drejtat e Tjera Sendore', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Mbrojtjen e Konsumatorit', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Mbrojtjen nga Diskriminimi', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Barazinë Gjinore', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Mbrojtjen e Fëmijës', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Personat me Aftësi të Kufizuara', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Banimin', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Shtetësinë', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për të Huajt', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Azilin', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Statusin Civil (lindje, martesë, vdekje)', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Asistencën Sociale', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Punësimin e Personave me Aftësi të Kufizuara', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Veteranët e UÇK-së', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Familjet e Dëshmorëve', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Personat me Statusin e Viktimës së Dhunës Seksuale gjatë Luftës', 'Akt ligjor / kod'),
    ('Ligje me Ndikim Direkt te Qytetarët', 'Ligji për Mbrojtjen nga Dhuna në Familje', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Arsimin Parauniversitar', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Arsimin e Lartë', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Arsimin Profesional', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Arsimin e të Rriturve', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Shkencën dhe Hulumtimin', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Inspektoratin e Arsimit', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Kulturën', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Trashëgiminë Kulturore', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Bibliotekat', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Muzetë', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Rininë', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Sportin', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Cinematografinë', 'Akt ligjor / kod'),
    ('Arsim, Kulturë, Rini, Sport', 'Ligji për Përdorimin e Gjuhëve (shqip, serbisht, gjuhët e pakicave)', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Shëndetësinë', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Barnat dhe Pajisjet Mjekësore', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Profesionet Shëndetësore', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Shëndetin Mendor', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Donacionin dhe Transplantimin e Organeve', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Shëndetin Riprodhues', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Mbrojtjen nga Sëmundjet Ngjitëse', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Kontrollin e Duhanit', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për Sigurinë e Pacientit', 'Akt ligjor / kod'),
    ('Shëndetësi', 'Ligji për të Drejtat dhe Përgjegjësitë e Qytetarëve në Kujdesin Shëndetësor', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Mbrojtjen e Mjedisit', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Vlerësimin e Ndikimit në Mjedis', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Mbrojtjen e Ajrit', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Ujërat', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Menaxhimin e Mbeturinave', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Bujqësinë', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Tokën Bujqësore', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Pyjet', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Veterinarinë', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Ushqimin', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Pijet Alkoolike', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Mbrojtjen e Bimëve', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Verën', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Peshkimin dhe Akuakulturën', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Gjuetinë', 'Akt ligjor / kod'),
    ('Mjedis, Bujqësi, Pyje', 'Ligji për Parqet Kombëtare', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Energjinë', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Energjinë Elektrike', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Energjinë Termike', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Burimet e Ripërtëritshme', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Efiçiencën e Energjisë', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Komunikimet Elektronike', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Shërbimet e Medias Audiovizuele', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për RTK (Radio Televizioni i Kosovës)', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Transportin Rrugor', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Sigurinë në Trafikun Rrugor', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Transportin e Mallrave të Rrezikshme', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Aviacionin Civil', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Hekurudhat', 'Akt ligjor / kod'),
    ('Energji, Telekomunikacion, Transport', 'Ligji për Postën', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Agjencinë Kundër Korrupsionit', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Parandalimin e Konfliktit të Interesit', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Deklarimin, Origjinën dhe Kontrollin e Pasurisë', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Mbrojtjen e Sinjalizuesve (whistleblowers)', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Parandalimin e Pastrimit të Parave dhe Financimit të Terrorizmit', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Konfiskimin e Pasurisë së Fituar me Vepër Penale', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Prokurimin Publik', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Qasje në Dokumente Publike', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Mbrojtjen e të Dhënave Personale', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Auditimin e Brendshëm të Sektorit Publik', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Zyrën Kombëtare të Auditimit', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Lobimin', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Sigurinë Kibernetike', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Krimet Kibernetike', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Bashkëpunimin Juridik Ndërkombëtar në Çështje Penale', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Ekstradicionin', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Mbrojtjen e Dëshmitarëve', 'Akt ligjor / kod'),
    ('Ligje për Sundimin e Ligjit dhe Korrupsionin', 'Ligji për Programin për Mbrojtjen e Dëshmitarëve', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Shërbimin Civil të Republikës së Kosovës', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Pagat e Funksionarëve Publikë', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Gjykatat', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Këshillin Gjyqësor të Kosovës', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Këshillin Prokurorial të Kosovës', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Prokurorinë e Shtetit', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Avokatin e Popullit (Ombudsperson)', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Vetëqeverisjen Lokale', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Kuvendin e Komunave', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Financimin e Vetëqeverisjes Lokale', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Zgjedhjet e Përgjithshme', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Zgjedhjet Lokale', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Partitë Politike', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Financimin e Subjekteve Politike', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Komisionin Qendror të Zgjedhjeve (KQZ)', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Policinë', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Inspektoratin Policor', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Agjencinë e Kosovës për Inteligjencë (AKI)', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Forcën e Sigurisë së Kosovës (FSK)', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Doganat', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Inspektoratin e Punës', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Inspektoratin Shëndetësor', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Notariatin', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Avokaturën', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Përmbarues Privatë', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Ndërmjetësim', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Arbitrazh', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Ndihmë Juridike Falas', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për Diasporën', 'Akt ligjor / kod'),
    ('Ligje për Institucionet dhe Administratën', 'Ligji për të Drejtën e Votës së Diasporës', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Shoqëritë Tregtare', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Regjistrimin e Bizneseve', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Falimentimin', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Bankat, Institucionet Mikrofinanciare dhe Institucionet Financiare Jobankare', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Bankën Qendrore të Republikës së Kosovës', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Kontabilitetin, Raportimin Financiar dhe Auditimin', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Tregjet e Kapitalit', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Investimet e Huaja', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Konkurrencën', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Pronësinë Intelektuale', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Patentat', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Markat Tregtare', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Dizajnin Industrial', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për të Drejtën e Autorit', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Turizmin', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Veprimtaritë Hoteliere dhe Restoratoria', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Promovimin e Investimeve të Huaja', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Lojërat e Fatit', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Statistikat Zyrtare', 'Akt ligjor / kod'),
    ('Ligje për Ekonominë dhe Biznesin', 'Ligji për Detyrimet dhe Kontratat', 'Akt ligjor / kod'),
    ('Ligje për Integrimin në BE', 'Teksti i plotë i MSA — Marrëveshja e Stabilizim-Asociimit', 'Material referues'),
    ('Ligje për Integrimin në BE', 'Plani Kombëtar për Zbatimin e MSA-së (PKZMSA)', 'Material referues'),
    ('Ligje për Integrimin në BE', 'Strategjia për Integrim Evropian (versioni i fundit)', 'Material referues'),
    ('Ligje për Integrimin në BE', 'Programi Kombëtar për Adoptimin e Acquis (PKAA)', 'Objektiv / integrim BE'),
    ('Ligje për Integrimin në BE', 'Plani i Veprimit për Liberalizimin e Vizave', 'Material referues'),
    ('Ligje për Integrimin në BE', 'Plani i Veprimit për Kapitullin 23', 'Objektiv / integrim BE'),
    ('Ligje për Integrimin në BE', 'Plani i Veprimit për Kapitullin 24', 'Objektiv / integrim BE'),
    ('Ligje për Integrimin në BE', 'Programet IPA (financim nga BE)', 'Objektiv / integrim BE'),
    ('Ligje për Integrimin në BE', 'Marrëveshjet sektoriale me BE-në', 'Material referues'),
    ('Akte Nënligjore', 'Rregulloret kryesore të Qeverisë', 'Material referues'),
    ('Akte Nënligjore', 'Udhëzimet Administrative të ministrive (sipas temës)', 'Objektiv / integrim BE'),
    ('Akte Nënligjore', 'Vendimet kryesore të Gjykatës Kushtetuese', 'Material referues'),
    ('Akte Nënligjore', 'Praktika gjyqësore e Gjykatës Supreme', 'Material referues'),
    ('Akte Nënligjore', 'Mendimet e Avokatit të Popullit', 'Material referues'),
    ('Akte Nënligjore', 'Mendimet e Institutit Gjyqësor të Kosovës', 'Material referues'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Si funksionon Kuvendi i Kosovës — procesi legjislativ hap pas hapi', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Si miratohet një ligj (nga propozimi në publikim në Gazetën Zyrtare)', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Iniciativa qytetare (si propozojnë qytetarët ligje)', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Konsultimet publike — si merr pjesë qytetari', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Si funksionon Qeveria — Kabineti, ministritë, agjencitë', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Si funksionon sistemi gjyqësor — instancat e gjykatave', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Diferenca mes komunës dhe qeverisë qendrore', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Sistemi zgjedhor i Kosovës', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'E drejta dhe detyrat e qytetarit', 'Udhëzues qytetar'),
    ('Procesi Legjislativ dhe Edukimi Qytetar', 'Kushtetuta e shpjeguar thjeshtë (për të rinj dhe fëmijë)', 'Akt ligjor / kod'),
    ('Raporte Zyrtare', 'Raporti vjetor i Komisionit Evropian për Kosovën (më i fundit)', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raporti i Progresit për Liberalizim Vizash', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet vjetore të Avokatit të Popullit', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet vjetore të Agjencisë Kundër Korrupsionit', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet vjetore të Këshillit Gjyqësor', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet vjetore të Këshillit Prokurorial', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet vjetore të Zyrës Kombëtare të Auditimit', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet e Bankës Qendrore', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet e Agjencisë së Statistikave të Kosovës (ASK)', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Indeksi i Perceptimit të Korrupsionit (Transparency International)', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet e Freedom House për Kosovën', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet e Reporterëve pa Kufij (liria e medias)', 'Raport zyrtar'),
    ('Raporte Zyrtare', 'Raportet e BIRN dhe KDI (organizatat vendore)', 'Raport zyrtar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të ushtroj të drejtat e mia" (për secilën temë)', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të raportoj korrupsion"', 'Raport zyrtar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Regjistrim biznesi', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Pasaportë / letërnjoftim', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Patentë shoferi', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Certifikatë lindje / martese / vdekje', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Regjistrim prone', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Leje ndërtimi', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Numër personal / numër fiskal', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Regjistrim makine', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Procedurat administrative bazë"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të ankohem ndaj një vendimi administrativ"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të paraqitem në gjykatë si dëshmitar / palë / i pandehur"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Të drejtat gjatë ndalimit nga policia"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Të drejtat e punëtorëve" (orari, pushimi, paga minimale)', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Të drejtat e konsumatorit"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Të drejtat e qiramarrësit dhe qiradhënësit"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Procedurat e divorcit dhe kujdestaria"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Procedurat e trashëgimisë"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Procedurat e ndarjes së pasurisë"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Procedurat e divorcit ndërkombëtar"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Të drejtat e diasporës" (votim, pasuri, shtetësi)', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të aplikoj për shtetësi kosovare"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të aplikoj për azil ose leje qëndrimi"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të raportoj dhunën në familje"', 'Raport zyrtar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Të drejtat e personave me aftësi të kufizuara"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Të drejtat e fëmijëve"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues "Si të marrë ndihmë juridike falas"', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues për procedurat tatimore për biznesit', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Udhëzues për startupet dhe bizneset e reja', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Përmbledhje të reformave kryesore (1-2 faqe secila)', 'Udhëzues qytetar'),
    ('Dokumente Shpjeguese për Qytetarët', 'Fjalor i termave ligjorë në shqip të thjeshtë', 'Udhëzues qytetar'),
    ('Pyetje të Shpeshta (FAQ)', 'Të drejtat e qytetarëve', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Reforma administrative', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Korrupsioni dhe si raportohet', 'Raport zyrtar'),
    ('Pyetje të Shpeshta (FAQ)', 'Integrimi në BE', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Ligje konkrete (punë, familje, tatime, pronë, biznes)', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Procedura gjyqësore', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Procedura administrative', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Shtetësia dhe dokumentet', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Diaspora', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Sigurimi shëndetësor dhe pensional', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Arsimi dhe e drejta për shkollim', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Të drejtat e pakicave dhe gjuhët zyrtare', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Mjedisi dhe planifikimi urban', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'E drejta e votës dhe sistemi zgjedhor', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Lista e 30-50+ pyetjeve me përgjigje të shkurtra, të ndara në kategori:', 'FAQ / bazë pyetjesh'),
    ('Pyetje të Shpeshta (FAQ)', 'Formati i preferuar: Excel me kolonat — Pyetja | Përgjigja | Kategoria | Burimi ligjor (neni / ligji)', 'FAQ / bazë pyetjesh'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa Evropiane për të Drejtat e Njeriut (KEDNj)', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Karta e të Drejtave Themelore të BE-së', 'Material referues'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Deklarata Universale për të Drejtat e Njeriut', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Pakti Ndërkombëtar për të Drejtat Civile dhe Politike', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Pakti Ndërkombëtar për të Drejtat Ekonomike, Sociale dhe Kulturore', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa kundër Torturës', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa për të Drejtat e Fëmijës', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa për Eliminimin e Diskriminimit ndaj Grave (CEDAW)', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa e Stambollit (dhuna ndaj grave)', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa e Kombeve të Bashkuara kundër Korrupsionit (UNCAC)', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa për të Drejtat e Personave me Aftësi të Kufizuara', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventa Evropiane për Mbrojtjen e Pakicave Kombëtare', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Konventat e Gjenevës (e drejta humanitare)', 'Dokument ndërkombëtar'),
    ('Të Drejtat e Njeriut dhe Dokumente Ndërkombëtare', 'Praktika gjyqësore e Gjykatës Evropiane për të Drejtat e Njeriut (raste që përfshijnë Kosovën ose Ballkanin)', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'CEFTA — Marrëveshja e Tregtisë së Lirë në Evropën Qendrore', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'Marrëveshja për Komunitetin e Energjisë', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'Marrëveshje bilaterale për ridmisión', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'Marrëveshjet me NATO / KFOR', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'Marrëveshjet bilaterale për shkëmbim të të dhënave', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'Marrëveshjet me EULEX', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'Marrëveshjet me UNMIK (historike)', 'Material referues'),
    ('Marrëveshje Ndërkombëtare të Kosovës', 'Marrëveshjet për heqjen e dyfishimit të taksave', 'Material referues'),
    ('Infografika dhe Statistika', '% e ligjeve të harmonizuara me Acquis (sipas kapitullit)', 'Objektiv / integrim BE'),
    ('Infografika dhe Statistika', 'Numri i reformave të kompletuara vs. të mbetura', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Timeline i ngjarjeve kryesore (1999, 2008, 2016, 2022, 2024)', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Hartë e progresit të Ballkanit Perëndimor në integrimin BE', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Organogrami i institucioneve të Kosovës', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Procesi legjislativ — diagram hap pas hapi', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Procesi i aderimit në BE — diagram', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Hartë e komunave të Kosovës', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Statistika të Agjencisë Kundër Korrupsionit (raste, dënime)', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Statistika gjyqësore (numri i lëndëve, kohëzgjatja mesatare)', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Statistika ekonomike (PBB, papunësia, investimet e huaja)', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Statistika demografike (popullsia, mosha, arsimi)', 'Infografikë / dataset'),
    ('Infografika dhe Statistika', 'Statistika të Agjencisë së Statistikave të Kosovës (ASK)', 'Infografikë / dataset'),
    ('Kontakte Praktike (numra dhe institucione)', 'Lista e zyrave të Avokatit të Popullit në komuna', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Linjat telefonike për raportim korrupsioni (AKK, prokurori)', 'Raport zyrtar'),
    ('Kontakte Praktike (numra dhe institucione)', 'Kontakte për ndihmë juridike falas (Agjencia për Ndihmë Juridike Falas)', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Linjat SOS për dhunë në familje', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Klinikat juridike falas pranë fakulteteve juridike', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Kontakte për mbrojtje konsumatori', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Kontakte për ankesa ndaj policisë (Inspektorati Policor)', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Numrat e emergjencës (112, 192, 193, 194)', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Zyrat komunale për shërbime qytetare', 'Kontakt praktik'),
    ('Kontakte Praktike (numra dhe institucione)', 'Pikat e kontaktit për diasporën', 'Kontakt praktik'),
    ('Glosar / Fjalorë', 'Fjalor i termave të BE-së (shqip / anglisht / serbisht)', 'Glosar'),
    ('Glosar / Fjalorë', 'Fjalor i termave juridikë (shpjegime në gjuhë të thjeshtë)', 'Glosar'),
    ('Glosar / Fjalorë', 'Akronimet kryesore (MSA, PKAA, KGJK, KPK, AKK, ZKA, ASK, FSK, AKI, KQZ, etj.)', 'Glosar'),
    ('Glosar / Fjalorë', 'Fjalor i termave administrativë', 'Glosar'),
    ('Glosar / Fjalorë', 'Fjalor i termave ekonomikë dhe tatimorë', 'Glosar')
), enriched as (
  select
    category,
    title,
    material_type,
    case
      when material_type = 'Akt ligjor / kod' then 'Gazeta Zyrtare e Republikës së Kosovës'
      when position('BE' in category) > 0 or position('Acquis' in title) > 0 or position('MSA' in title) > 0 or position('Kapitulli' in title) > 0 then 'Komisioni Evropian'
      when material_type = 'Infografikë / dataset' or position('Statistika' in title) > 0 then 'Agjencia e Statistikave të Kosovës'
      when position('Avokatit të Popullit' in title) > 0 then 'Avokati i Popullit'
      when position('Korrupsion' in title) > 0 or position('korrupsion' in title) > 0 then 'Agjencia për Parandalimin e Korrupsionit'
      when position('Gjyqësor' in title) > 0 or position('gjyqësor' in title) > 0 then 'Këshilli Gjyqësor i Kosovës'
      when position('Prokurorial' in title) > 0 or position('prokurorial' in title) > 0 then 'Këshilli Prokurorial i Kosovës'
      else 'Burim zyrtar institucional'
    end as source_label,
    case
      when material_type = 'Akt ligjor / kod' then 'https://gzk.rks-gov.net/'
      when position('BE' in category) > 0 or position('Acquis' in title) > 0 or position('MSA' in title) > 0 or position('Kapitulli' in title) > 0 then 'https://enlargement.ec.europa.eu/countries/kosovo_en'
      when material_type = 'Infografikë / dataset' or position('Statistika' in title) > 0 then 'https://ask.rks-gov.net/'
      when position('Avokatit të Popullit' in title) > 0 then 'https://oik-rks.org/'
      when position('Korrupsion' in title) > 0 or position('korrupsion' in title) > 0 then 'https://www.akk-ks.org/'
      when position('Gjyqësor' in title) > 0 or position('gjyqësor' in title) > 0 then 'https://www.gjyqesori-rks.org/'
      when position('Prokurorial' in title) > 0 or position('prokurorial' in title) > 0 then 'https://prokuroria-rks.org/'
      else 'https://www.rks-gov.net/'
    end as source_url,
    case
      when material_type = 'Akt ligjor / kod' then 'Material ligjor i futur; hap burimin zyrtar dhe verifiko versionin e konsoliduar/amendamentet para citimit.'
      when position('BE' in category) > 0 then 'Material i integrimit në BE; krahaso statusin me raportin më të fundit të Komisionit Evropian.'
      when material_type = 'Raport zyrtar' then 'Raport/dataset i futur; verifiko vitin më të fundit para publikimit final.'
      else 'Material referues i futur në CMS; kërkon kontroll final editorial para publikimit.'
    end as status
  from raw
), payload as (
  select jsonb_build_object(
    'key', 'materials_catalog',
    'items', jsonb_agg(jsonb_build_object(
      'category', category,
      'title', title,
      'slug', left(regexp_replace(lower(title), '[^a-z0-9]+', '-', 'g'), 96),
      'material_type', material_type,
      'summary_sq', material_type,
      'source_label', source_label,
      'source_url', source_url,
      'status', status
    ) order by category, title)
  ) as content
  from enriched
)
insert into page_blocks (page_slug, type, title, content, sort_order, published)
select 'sundimi', 'collection', 'Full materials catalog', content, 33, true from payload;
